name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material markdown-include mkdocs-markdownextradata-plugin inginious pydantic
      - run: cd docs && python scripts/generate_categories.py
      - run: cd docs && mkdocs gh-deploy --force
